export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const GET_USER_DATA= 'GET_USER_DATA';

export const CREATE_LIST_SUCCESS= "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAILURE= "CREATE_LIST_FAILURE";
export const GET_LIST = 'GET_LIST';

export const DELETE_LIST_SUCCESS= "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAILURE= "DELETE_LIST_FAILURE";


export const SAVE_LINK = 'SAVE_LINK';
export const GET_LINK = 'GET_LINK';
export const GET_ALL_LINKS = 'GET_ALL_LINKS';

export const DELETE_LINK_LOADING = 'DELETE_LINK_LOADING';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';

export const GET_SELECTED_HASH_LINKS = 'GET_SELECTED_HASH_LINKS';
